"""Add employee_time_sheet table

Revision ID: 6f3a7c1c198f
Revises: 
Create Date: 2022-05-01 23:55:46.252758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3a7c1c198f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_time_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.DATE(), nullable=False),
    sa.Column('hrs', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_time_sheet_id'), 'employee_time_sheet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_time_sheet_id'), table_name='employee_time_sheet')
    op.drop_table('employee_time_sheet')
    # ### end Alembic commands ###
